export const ADD_INGREDIENT =  'ADD_INGREDIENT';
export const REMOVE_INGREDIENT =  'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const SET_INGREDIENTS_FAILED = 'SET_INGREDIENTS_FAILED';

export const PURSHASE_BURGER_SUCCESS = 'PURSHASE_BURGER_SUCCESS';
export const PURSHASE_BURGER_FAILED = 'PURSHASE_BURGER_FAILED';
export const PURSHASE_BURGER_START = 'PURSHASE_BURGER_START';
export const PURSHASE_INIT = 'PURSHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';